In [1]:
import pandas as pd

In [2]:
d1 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,9,10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,22,23,24]
}

In [3]:
df1 = pd.DataFrame(d1)

In [4]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [5]:
d2 = d2 = {'key1':[1,2,3,4,5,"yash"],
      'key2' : [7,8,9,"mohite",11,12],
      'key3':[13,14,15,"isha",17,18],
      'key4':[19,20,21,22,23,24]
}

In [6]:
df2 = pd.DataFrame(d2)

In [7]:
df2

key1    key2  key3  key4
0     1       7    13    19
1     2       8    14    20
2     3       9    15    21
3     4  mohite  isha    22
4     5      11    17    23
5  yash      12    18    24

In [8]:
# marge operation work
pd.merge(df1,df2)#whataever is common value in data  it will give you

key1 key2 key3  key4
0    1    7   13    19
1    2    8   14    20
2    3    9   15    21
3    5   11   17    23

In [9]:
pd.merge(df1,df2,how="inner",on="key1")#paramaters

key1  key2_x  key3_x  key4_x  key2_y key3_y  key4_y
0    1       7      13      19       7     13      19
1    2       8      14      20       8     14      20
2    3       9      15      21       9     15      21
3    4      10      16      22  mohite   isha      22
4    5      11      17      23      11     17      23

In [10]:
pd.merge(df1,df2,how="inner",on="key4")

key1_x  key2_x  key3_x  key4 key1_y  key2_y key3_y
0      1       7      13    19      1       7     13
1      2       8      14    20      2       8     14
2      3       9      15    21      3       9     15
3      4      10      16    22      4  mohite   isha
4      5      11      17    23      5      11     17
5   sudh      12      18    24   yash      12     18

In [11]:
# leftmearge operation
pd.merge(df1,df2,how="left",on="key4")#take left side data 

key1_x  key2_x  key3_x  key4 key1_y  key2_y key3_y
0      1       7      13    19      1       7     13
1      2       8      14    20      2       8     14
2      3       9      15    21      3       9     15
3      4      10      16    22      4  mohite   isha
4      5      11      17    23      5      11     17
5   sudh      12      18    24   yash      12     18

In [12]:
pd.merge(df1,df2,how="right",on="key1")

C:\Users\yash mohite\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\reshape\merge.py:916: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  key_col = Index(lvals).where(~mask_left, rvals)


key1  key2_x  key3_x  key4_x  key2_y key3_y  key4_y
0   1.0     7.0    13.0    19.0       7     13      19
1   2.0     8.0    14.0    20.0       8     14      20
2   3.0     9.0    15.0    21.0       9     15      21
3   4.0    10.0    16.0    22.0  mohite   isha      22
4   5.0    11.0    17.0    23.0      11     17      23
5  yash     NaN     NaN     NaN      12     18      24

In [13]:
pd.merge(df1,df2,how="outer",on="key1")

key1  key2_x  key3_x  key4_x  key2_y key3_y  key4_y
0     1     7.0    13.0    19.0       7     13    19.0
1     2     8.0    14.0    20.0       8     14    20.0
2     3     9.0    15.0    21.0       9     15    21.0
3     4    10.0    16.0    22.0  mohite   isha    22.0
4     5    11.0    17.0    23.0      11     17    23.0
5  sudh    12.0    18.0    24.0     NaN    NaN     NaN
6  yash     NaN     NaN     NaN      12     18    24.0

In [14]:
pd.merge(df1,df2,how="outer",on=["key1","key3"])

C:\Users\yash mohite\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\reshape\merge.py:916: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  key_col = Index(lvals).where(~mask_left, rvals)


key1  key2_x  key3  key4_x  key2_y  key4_y
0     1     7.0  13.0    19.0       7    19.0
1     2     8.0  14.0    20.0       8    20.0
2     3     9.0  15.0    21.0       9    21.0
3     4    10.0  16.0    22.0     NaN     NaN
4     5    11.0  17.0    23.0      11    23.0
5  sudh    12.0  18.0    24.0     NaN     NaN
6     4     NaN  isha     NaN  mohite    22.0
7  yash     NaN    18     NaN      12    24.0

In [15]:
d3 = {'a':[1,2,3,4,5,"sudh"],
      'b' : [7,8,9,10,11,12],
      'c':[13,14,15,16,17,18],
      'd':[19,20,21,22,23,24]
}

In [16]:
d4 = {'key1':[1,2,3,4,5,"yash"],
      'key2' : [7,8,9,"mohite",11,12],
      'key3':[13,14,15,"isha",17,18],
      'key4':[19,20,21,22,23,24]
}

In [17]:
df3 = pd.DataFrame(d3)

In [18]:
df3

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [19]:
df4 = pd.DataFrame(d4)

In [20]:
df4

key1    key2  key3  key4
0     1       7    13    19
1     2       8    14    20
2     3       9    15    21
3     4  mohite  isha    22
4     5      11    17    23
5  yash      12    18    24

In [21]:
pd.merge(df3,df4,how="left",left_on="a",right_on="key1")

a   b   c   d key1    key2  key3  key4
0     1   7  13  19    1       7    13  19.0
1     2   8  14  20    2       8    14  20.0
2     3   9  15  21    3       9    15  21.0
3     4  10  16  22    4  mohite  isha  22.0
4     5  11  17  23    5      11    17  23.0
5  sudh  12  18  24  NaN     NaN   NaN   NaN

In [22]:
df3

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [23]:
df4

key1    key2  key3  key4
0     1       7    13    19
1     2       8    14    20
2     3       9    15    21
3     4  mohite  isha    22
4     5      11    17    23
5  yash      12    18    24

In [24]:
# how : {'left', 'right', 'outer', 'inner'}, default 'left'
#     How to handle the operation of the two objects.

In [25]:
# join operation join 2 dataframe in onedata frame
df3.join(df4)

a   b   c   d  key1    key2  key3  key4
0     1   7  13  19     1       7    13    19
1     2   8  14  20     2       8    14    20
2     3   9  15  21     3       9    15    21
3     4  10  16  22     4  mohite  isha    22
4     5  11  17  23     5      11    17    23
5  sudh  12  18  24  yash      12    18    24

In [26]:
df3.join(df4,how="outer")#take all  the combination left and right

a   b   c   d  key1    key2  key3  key4
0     1   7  13  19     1       7    13    19
1     2   8  14  20     2       8    14    20
2     3   9  15  21     3       9    15    21
3     4  10  16  22     4  mohite  isha    22
4     5  11  17  23     5      11    17    23
5  sudh  12  18  24  yash      12    18    24

In [27]:
df3.join(df4,how="inner")

a   b   c   d  key1    key2  key3  key4
0     1   7  13  19     1       7    13    19
1     2   8  14  20     2       8    14    20
2     3   9  15  21     3       9    15    21
3     4  10  16  22     4  mohite  isha    22
4     5  11  17  23     5      11    17    23
5  sudh  12  18  24  yash      12    18    24

In [28]:
df3.join(df4,how="left")

a   b   c   d  key1    key2  key3  key4
0     1   7  13  19     1       7    13    19
1     2   8  14  20     2       8    14    20
2     3   9  15  21     3       9    15    21
3     4  10  16  22     4  mohite  isha    22
4     5  11  17  23     5      11    17    23
5  sudh  12  18  24  yash      12    18    24

In [29]:
df3.join(df4,how="right")

a   b   c   d  key1    key2  key3  key4
0     1   7  13  19     1       7    13    19
1     2   8  14  20     2       8    14    20
2     3   9  15  21     3       9    15    21
3     4  10  16  22     4  mohite  isha    22
4     5  11  17  23     5      11    17    23
5  sudh  12  18  24  yash      12    18    24

In [30]:
# the differencr bitewwn mearge and joinj is join mataches indexex and 
# merge check the column value matches

In [31]:
pd.concat([df3,df4],axis=0) #--rowwise concation

a     b     c     d  key1    key2  key3  key4
0     1   7.0  13.0  19.0   NaN     NaN   NaN   NaN
1     2   8.0  14.0  20.0   NaN     NaN   NaN   NaN
2     3   9.0  15.0  21.0   NaN     NaN   NaN   NaN
3     4  10.0  16.0  22.0   NaN     NaN   NaN   NaN
4     5  11.0  17.0  23.0   NaN     NaN   NaN   NaN
5  sudh  12.0  18.0  24.0   NaN     NaN   NaN   NaN
0   NaN   NaN   NaN   NaN     1       7    13  19.0
1   NaN   NaN   NaN   NaN     2       8    14  20.0
2   NaN   NaN   NaN   NaN     3       9    15  21.0
3   NaN   NaN   NaN   NaN     4  mohite  isha  22.0
4   NaN   NaN   NaN   NaN     5      11    17  23.0
5   NaN   NaN   NaN   NaN  yash      12    18  24.0

In [32]:
pd.concat([df3,df4],axis=1) #|colum vise concation

a   b   c   d  key1    key2  key3  key4
0     1   7  13  19     1       7    13    19
1     2   8  14  20     2       8    14    20
2     3   9  15  21     3       9    15    21
3     4  10  16  22     4  mohite  isha    22
4     5  11  17  23     5      11    17    23
5  sudh  12  18  24  yash      12    18    24

## Numpy

In [33]:
import numpy as np

In [34]:
l = [1,2,3,6,5,4,7,8,9]

In [35]:
type(l)

list

In [36]:
a = np.array(l)# array function convert list in to array

In [37]:
a

array([1, 2, 3, 6, 5, 4, 7, 8, 9])

In [38]:
type(a)

numpy.ndarray

In [39]:
a1 = np.array([[1,2,3],[4,5,6]])

In [40]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a1.ndim # function show you the diminsion of array

2

In [42]:
a3 = np.array([[[1,2,6,4,7],[1,4,8,6,2]]])

In [43]:
a3

array([[[1, 2, 6, 4, 7],
        [1, 4, 8, 6, 2]]])

In [44]:
a3.ndim

3

In [45]:
a4 = np.array([[[[1,2,6,4,7],[1,4,8,6,2]]]])

In [46]:
a4

array([[[[1, 2, 6, 4, 7],
         [1, 4, 8, 6, 2]]]])

In [47]:
a4.ndim

4

In [48]:
a

array([1, 2, 3, 6, 5, 4, 7, 8, 9])

In [49]:
l

[1, 2, 3, 6, 5, 4, 7, 8, 9]

In [50]:
a = np.asarray(l)# asarray also convery array 

In [51]:
a

array([1, 2, 3, 6, 5, 4, 7, 8, 9])

In [52]:
#matrix function convery any array and list in matrix and convert in two diminsion array
m = np.matrix(l)

In [53]:
m

matrix([[1, 2, 3, 6, 5, 4, 7, 8, 9]])

In [54]:
a

array([1, 2, 3, 6, 5, 4, 7, 8, 9])

In [55]:
np.asanyarray(a)#this keep as it is  if pass ayyar and metrix

array([1, 2, 3, 6, 5, 4, 7, 8, 9])

In [56]:
np.asanyarray(m)

matrix([[1, 2, 3, 6, 5, 4, 7, 8, 9]])

In [57]:
a1 = a #shallow copy method

In [58]:
a1

array([1, 2, 3, 6, 5, 4, 7, 8, 9])

In [59]:
a1[2] = 30

In [60]:
a

array([ 1,  2, 30,  6,  5,  4,  7,  8,  9])

In [61]:
a1[6] = 700

In [62]:
a

array([  1,   2,  30,   6,   5,   4, 700,   8,   9])

In [63]:
# this is call deep copy method
a2 = np.copy(a)#copy function copy the data in array

In [64]:
a2[5] = 500

In [65]:
a2

array([  1,   2,  30,   6,   5, 500, 700,   8,   9])

In [66]:
a

array([  1,   2,  30,   6,   5,   4, 700,   8,   9])

In [67]:
#from function generate data work for 2d
np.fromfunction(lambda x,y: x == y,(5,6))

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False]])

In [68]:
# generat > rows > column
np.random.rand(2,2,2)# this function generate data from given value

array([[[0.49058192, 0.22878499],
        [0.60052689, 0.51100605]],

       [[0.99834895, 0.29247917],
        [0.01057228, 0.5801665 ]]])

In [69]:
np.random.rand(3,4,3)

array([[[0.01529433, 0.53226847, 0.06956025],
        [0.17939381, 0.67824831, 0.67596372],
        [0.47386172, 0.26891259, 0.86707135],
        [0.5278553 , 0.96228673, 0.45502777]],

       [[0.45162532, 0.06862865, 0.05476966],
        [0.99369802, 0.81421956, 0.01253284],
        [0.21096998, 0.52093156, 0.40250448],
        [0.17892855, 0.58186668, 0.26471355]],

       [[0.30664397, 0.44038911, 0.86960253],
        [0.54983424, 0.18416827, 0.28371455],
        [0.22145007, 0.21505587, 0.17182106],
        [0.32901861, 0.79814582, 0.84875597]]])

In [70]:
np.random.rand(2,3,2,2)

array([[[[0.41546615, 0.60696308],
         [0.0625805 , 0.45218033]],

        [[0.95761343, 0.77124835],
         [0.09620078, 0.29223082]],

        [[0.54834049, 0.20973128],
         [0.05519574, 0.15979525]]],


       [[[0.88851549, 0.63384037],
         [0.90412081, 0.41613801]],

        [[0.21967118, 0.16227241],
         [0.16248352, 0.32247839]],

        [[0.74235059, 0.83887   ],
         [0.59784982, 0.06723799]]]])

In [71]:
#Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(2,2,3)

array([[[-0.85891975, -0.39525708,  0.62468054],
        [ 1.03917718,  0.33552324,  0.1520042 ]],

       [[-0.13933529, -0.81906584, -0.46161069],
        [-0.29873547, -0.98605856,  0.68616864]]])

In [72]:
#generate int value data acoding low to high  value
np.random.randint(1,10000,(2,2,3))

array([[[6258,  140, 8037],
        [ 565,  685, 4775]],

       [[  90, 6620, 5860],
        [1851, 5533, 3213]]])

In [78]:
data = np.random.rand(5,5)

In [79]:
pd.DataFrame(data)

0         1         2         3         4
0  0.318399  0.967579  0.206685  0.745765  0.930853
1  0.085381  0.393296  0.908582  0.061491  0.763180
2  0.152923  0.623417  0.782263  0.146979  0.809403
3  0.675083  0.070463  0.062166  0.188637  0.638752
4  0.147265  0.085303  0.304143  0.760940  0.747766

In [89]:
#reshpe finction convert anydiminsion data in to 2ddata
data2 = np.random.rand(2,4,4)

In [92]:
pd.DataFrame(data2.reshape(16,2))

0         1
0   0.930043  0.811117
1   0.720975  0.210414
2   0.168849  0.856212
3   0.062747  0.496452
4   0.312435  0.396207
5   0.968943  0.062975
6   0.047107  0.753350
7   0.057580  0.872645
8   0.166720  0.392747
9   0.349199  0.131593
10  0.189673  0.716855
11  0.010944  0.399465
12  0.599938  0.376363
13  0.695566  0.128231
14  0.883244  0.510356
15  0.491393  0.843910